/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.acrolinx.client.sdk;

import com.acrolinx.client.sdk.exceptions.SSOException;
import com.acrolinx.client.sdk.exceptions.SignInException;
import com.acrolinx.client.sdk.platform.Capabilities;

public class AcrolinxEndpoint {

    private String clientSignature;
    private String clientVersion;
    private String clientLocale;
    private String acrolinxURL;

    // use logger from sidebar-sdk
    public PlatformInformation getPlatformInformation(){
        // works without authentication

    }

    public SignInSuccess signInWithSSO(String genericToken, String username) throws SSOException
    {

    }

    public SignInSuccess singInInteractive(InteractiveCallback callback) throws SignInException
    {
        singInInteractive(callback, null);
    }

    public SignInSuccess singInInteractive(InteractiveCallback callback, String accessToken) throws SignInException
    {

    }

    public Capabilities getCapabilities(String accessToken) {

    }



}