name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  Sonar-Check:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Sonar Scan Project
        run: ./gradlew sonar

  Build-And-Deploy:
    runs-on: ubuntu-latest
    env:
      ACROLINX_URL: ${{ secrets.ACROLINX_URL }}
      ACROLINX_API_USERNAME: ${{ secrets.ACROLINX_API_USERNAME }}
      ACROLINX_API_TOKEN: ${{ secrets.ACROLINX_API_TOKEN }}
      ACROLINX_API_SSO_TOKEN: ${{ secrets.ACROLINX_API_SSO_TOKEN }}
      ACROLINX_DEV_SIGNATURE: ${{ secrets.ACROLINX_DEV_SIGNATURE }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.CODE_SIGNING_PWD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.CODE_SIGNING_PRIV_KEY }}
      SONATYPE_PW: ${{ secrets.SONATYPE_PW }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build Gradle Project
        run: ./gradlew build

      - name: Create Java Doc
        run: ./gradlew javadoc

      - name: Deploy artifacts
        id: deploy
        if: github.ref == 'refs/heads/main'
        run: ./deploy.sh

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.39.0
        if: steps.deploy.outputs.RELEASE == 'true' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ steps.deploy.outputs.TAGNAME }}

      - name: Deploy Java Doc
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        if: steps.deploy.outputs.RELEASE == 'true' && github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: "build/docs/javadoc/"
