name: GitHub Actions sdk-java
on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [master]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8'
      - run: ./gradlew build --exclude-task test && ./gradlew javadoc
      - run: chmod +x ./deploy.sh
