name: GitHub Actions sdk-java
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      ACROLINX_URL: ${{ secrets.ACROLINX_URL }}
      ACROLINX_API_USERNAME: ${{ secrets.ACROLINX_API_USERNAME }}
      ACROLINX_API_TOKEN: ${{ secrets.ACROLINX_API_TOKEN }}
      ACROLINX_API_SSO_TOKEN: ${{ secrets.ACROLINX_API_SSO_TOKEN }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.CODE_SIGNING_PWD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.CODE_SIGNING_PRIV_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8'

      - name: Build Gradle Project
        run: ./gradlew build

      - name: Create Java Doc
        run: ./gradlew javadoc

      - name: Deploy artifacts
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh

      - name: Deploy Java Doc
        uses: avinal/github-pages-deploy-action@main #For deployment of generated javadoc pages
        with:
          # GitHub access token with Repo Access
          GITHUB_TOKEN: ${{ github.token }}
          LANGUAGE: "java"
          PAGES_BRANCH: "gh-pages"
          BUILD_FROM: "master"
          DOCS_FOLDER: "build/docs/javadoc/"


          
