name: Release
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      GIT_USER_NAME: acrolinx-opensource
      GIT_USER_EMAIL: opensource@acrolinx.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout test-branch
        run: |
          git config user.name $GIT_USER_NAME
          git config user.email $GIT_USER_EMAIL
          git checkout -b test-branch
          touch file.txt
          echo "foo" >> file.txt
          git add file.txt
          git commit -m "Add file.txt"
          git push -u origin HEAD

      - name: Create GitHub PR
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git rev-parse --abbrev-ref HEAD
          gh pr create --title "Release $RELEASE_VERSION" --body "" --base main
          gh pr merge test-branch --auto --rebase --delete-branch
