name: Release Stable Version
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Release-Stable:
    runs-on: ubuntu-latest
    env:
      ACROLINX_URL: ${{ secrets.ACROLINX_URL }}
      ACROLINX_API_USERNAME: ${{ secrets.ACROLINX_API_USERNAME }}
      ACROLINX_API_TOKEN: ${{ secrets.ACROLINX_API_TOKEN }}
      ACROLINX_API_SSO_TOKEN: ${{ secrets.ACROLINX_API_SSO_TOKEN }}
      ACROLINX_DEV_SIGNATURE: ${{ secrets.ACROLINX_DEV_SIGNATURE }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.CODE_SIGNING_PWD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.CODE_SIGNING_PRIV_KEY }}
      SONATYPE_PW: ${{ secrets.SONATYPE_PW }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: 'jdk+fx'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Gradle build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - name: Create Javadoc
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: javadoc

      - name: Deploy artifacts
        id: deploy
        if: github.ref == 'refs/heads/main'
        run: ./deploy-stable.sh

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        if: steps.deploy.outputs.RELEASE == 'true' && github.ref == 'refs/heads/main'
        env:
          CUSTOM_TAG: ${{ steps.deploy.outputs.TAGNAME }}

      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        if: steps.deploy.outputs.RELEASE == 'true' && github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: "docs/"
